<?php
/**
 * @file
 * Code for the UCLALIB Static feature.
 */

include_once 'uclalib_static.features.inc';

/**
 * Implements hook_pathauto_alias_alter().
 *
 * Handles dynamic aliasing of location subpages.
 */
function uclalib_static_pathauto_alias_alter(&$alias, $context) {
  if ($context['module'] == 'node' && isset($context['data']['node'])) {
    $node = $context['data']['node'];

    if ($node->type == 'static') {
      if ($parent_node = uclalib_navigation_menu_get_parent($node)) {
        $parent_path = drupal_get_path_alias('node/' . $parent_node->nid);
        if (!empty($alias) && ($alias != 'node/' . $parent_node->nid)) {
          // The "at this parent" uses the special case /parent-url/destinations
          // the words 'at' and 'this' would be removed by PA and with just read /parent
          if ($node->panelizer['page_manager']->name == 'node:static:static_at_this_parent') {
            $alias = $parent_path . '/destinations';
          }
          else {
            // All other cases just append the parent url.
            $alias = $parent_path . '/' . $alias;
          }
        }
      }
    }
  }
}