name = UCLA Lib
description = The basic UCLA Library site template.
preview = preview.png
template = basic

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[colophon_first]   = Colophon first
regions[colophon_second]  = Colophon second
regions[colophon_third]   = Colophon third
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/basic/basic.layout.css
