<?php
/**
 * @file
 * Code for the UCLALIB Navigation feature.
 */

include_once 'uclalib_navigation.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function uclalib_navigation_ctools_plugin_directory($owner, $plugin_type) {
  switch ("$owner:$plugin_type") {
    case 'ctools:relationships':
    case 'ctools:content_types':
      return "plugins/$owner/$plugin_type";
  }

  return NULL;
}

/**
 * Get the parent node in the menu tree.
 *
 * @param $node
 * @return bool|mixed
 */
function uclalib_navigation_menu_get_parent($node) {

  // We need to clone the node as menu_node_prepare() may cause data loss.
  // @see http://drupal.org/node/1317926
  $menu_node = clone $node;
  menu_node_prepare($menu_node);
  if (isset($menu_node->menu['plid'])) {
    $pitem = menu_link_load($menu_node->menu['plid']);
    if ($pitem['router_path'] == 'node/%') {
      $matches = array();
      if (preg_match('/^node\/([0-9]+)$/', $pitem['link_path'], $matches)) {
        return node_load($matches[1]);
      }
    }
  }

  return FALSE;
}

/**
 * Get the about node in the menu tree.
 *
 * @param $node
 * @return bool|mixed
 */
function uclalib_navigation_menu_get_about($node) {

  // We need to clone the node as menu_node_prepare() may cause data loss.
  // @see http://drupal.org/node/1317926
  $menu_node = clone $node;
  menu_node_prepare($menu_node);
  if (isset($menu_node->menu['mlid'])) {
    $full_menu_items = menu_tree_all_data($menu_node->menu['menu_name']);
    foreach ($full_menu_items as $menu_item) {
      if ($menu_item['link']['mlid'] == $menu_node->menu['mlid']) {
        $links = $menu_item['below'];
        break;
      }
      else {

        // Also check sub-items.
        if (count($menu_item['below'])) {
          foreach ($menu_item['below'] as $menu_item) {
            if ($menu_item['link']['mlid'] == $menu_node->menu['mlid']) {
              $links = $menu_item['below'];
              break 2;
            }
          }
        }
      }
    }
    if (isset($links)) {
      foreach ($links as $link) {
        if ($link['link']['link_title'] == 'About') {
          $menu_item = menu_get_item($link['link']['link_path']);
          if (isset($menu_item['page_arguments'][0])) {
            return $menu_item['page_arguments'][0];
          }
        }
      }
    }
  }

  return FALSE;
}
