<?php
/**
 * @file
 * Code for the UCLALIB Navigation feature.
 */

include_once 'uclalib_navigation.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function uclalib_navigation_ctools_plugin_directory($owner, $plugin_type) {
  switch ("$owner:$plugin_type") {
    case 'ctools:relationships':
    case 'ctools:content_types':
      return "plugins/$owner/$plugin_type";
  }

  return NULL;
}

/**
 * Get the parent node in the menu tree.
 *
 * @param $node
 * @return bool|mixed
 */
function uclalib_navigation_menu_get_parent($node) {
  menu_node_prepare($node);
  if (isset($node->menu['plid'])) {
    $pitem = menu_link_load($node->menu['plid']);
    if ($pitem['router_path'] == 'node/%') {
      $matches = array();
      if (preg_match('/^node\/([0-9]+)$/', $pitem['link_path'], $matches)) {
        return node_load($matches[1]);
      }
    }
  }

  return FALSE;
}

/**
 * Get the about node in the menu tree.
 *
 * @param $node
 * @return bool|mixed
 */
function uclalib_navigation_menu_get_about($node) {
  menu_node_prepare($node);
  if (isset($node->menu['mlid'])) {
    $full_menu_items = menu_tree_all_data($node->menu['menu_name']);
    $pitem = menu_link_load($node->menu['plid']);
    foreach ($full_menu_items as $menu_item) {
      if ($menu_item['link']['mlid'] == $node->menu['mlid']) {
        $links = $menu_item['below'];
        break;
      }
    }
    foreach ($links as $link) {
      if ($link['link']['link_title'] == 'About') {
        $menu_item = menu_get_item($link['link']['link_path']);
        if (isset($menu_item['page_arguments'][0])) {
          return $menu_item['page_arguments'][0];
        }
      }
    }
  }

  return FALSE;
}
