<?php
/**
 * @file
 * uclalib_showcase.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function uclalib_showcase_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "bean_admin_ui" && $api == "bean") {
    return array("version" => "5");
  }
  if ($module == "panelizer" && $api == "panelizer") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}
