<?php
/**
 * @file
 * Provides access to extra attributes not supported by the shib_auth module.
 */

/**
 * Implements hook_user_insert
 * Capture Shibboleth attributes and add them to the account (user) being created.
 */
function ucla_shib_extras_user_insert(&$edit, $account, $category) {
  // At this point, $account has been created and $account->uid is valid.

  // Do the following only if certain HTTP headers are set by Shibboleth
  // HTTP_SHIBGIVENNAME = first name; HTTP_SHIBSN = last name
  if ( !empty($_SERVER['HTTP_SHIBGIVENNAME']) && !empty($_SERVER['HTTP_SN']) ) {
    $edit['field_user_first_name']['und'][0]['value'] = $_SERVER['HTTP_SHIBGIVENNAME'];
    $edit['field_user_last_name']['und'][0]['value'] = $_SERVER['HTTP_SHIBSN'];

    // Flag $edit array as existing, so saving will update instead of create (insert)
    $edit['is_new'] = FALSE;

    // Save the changes
    user_save($account, $edit);
  };
}

