<?php

/**
 * @file
 * Adds a panel pane style for collapsible regions and panes, on mobile devices.
 */

/*
 * Implements hook_ctools_plugin_directory().
 */
function panels_style_mobile_collapsible_ctools_plugin_directory($module, $plugin) {
  if (($module == 'panels' || $module == 'ctools') && $plugin == 'styles') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_theme()
 */
function panels_style_mobile_collapsible_theme() {
  return array(
    'mobile_collapsible' => array(
      'variables' => array('title' => NULL, 'content' => NULL, 'collapsed' => TRUE, 'custom_classes_array' => NULL, 'panel_pane_classes' => FALSE),
      'path' => drupal_get_path('module', 'panels_style_mobile_collapsible') . '/templates',
      'template' => 'mobile-collapsible',
    )
  );
}

/**
 * Support unique classes for panel panes as they are used for styling.
 */
function template_preprocess_mobile_collapsible(&$vars) {
  drupal_add_js(drupal_get_path('module', 'panels_style_mobile_collapsible') . '/javascript/mobile-collapsible.js');
  drupal_add_js(drupal_get_path('module', 'panels_style_mobile_collapsible') . '/javascript/mobile-collapsible-init.js');

  $vars['classes_array'] = array_merge($vars['classes_array'], $vars['custom_classes_array']);
}
