<?php
/**
 * @file
 * Code for the UCLALIB Resources feature.
 */

include_once 'uclalib_resources.features.inc';

/**
 * Implements hook_ctools_plugin_directory()
 */
function uclalib_resources_ctools_plugin_directory($owner, $plugin_type) {
  switch ("$owner:$plugin_type") {
    case 'ctools:content_types':
      return "plugins/$owner/$plugin_type";
  }

  return NULL;
}

/**
 * Implements hook_form_ID_alter().
 */
function uclalib_resources_form_views_exposed_form_alter(&$form, &$form_state) {
  // Move search field label to html5 placeholder.
  if ($form['submit']['#id'] == 'edit-submit-find-resources') {
    $form['title']['#attributes']['placeholder'] = $form['#info']['filter-title']['label'];
    $form['#info']['filter-title']['label'] = '';
  }
}
