<?php
/**
 * @file
 * uclalib_living_library_gallery.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function uclalib_living_library_gallery_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'bean-living_library_gallery-field_gallery_images'
  $field_instances['bean-living_library_gallery-field_gallery_images'] = array(
    'bundle' => 'living_library_gallery',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'fancybox',
        'settings' => array(
          'fancybox_caption' => 'auto',
          'fancybox_caption_custom' => '',
          'fancybox_gallery' => 'post',
          'fancybox_gallery_custom' => '',
          'fancybox_image_style_content' => 'widescreen_medium',
          'fancybox_image_style_fancybox' => 'widescreen_large',
        ),
        'type' => 'fancybox',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'bean',
    'field_name' => 'field_gallery_images',
    'label' => 'Gallery Images',
    'required' => 1,
    'settings' => array(
      'alt_field' => 1,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'insert' => 0,
        'insert_absolute' => 0,
        'insert_class' => '',
        'insert_default' => 'auto',
        'insert_styles' => array(
          'auto' => 'auto',
          'fancybox__category_icon' => 0,
          'fancybox__custom_crop' => 0,
          'fancybox__large' => 0,
          'fancybox__linkit_thumb' => 0,
          'fancybox__medium' => 0,
          'fancybox__thumbnail' => 0,
          'fancybox__thumbnail_crop' => 0,
          'fancybox__thumbnail_large' => 0,
          'fancybox__thumbnail_small' => 0,
          'fancybox__widescreen_crop' => 0,
          'fancybox__widescreen_large' => 0,
          'fancybox__widescreen_medium' => 0,
          'fancybox__widescreen_small' => 0,
          'icon_link' => 0,
          'image' => 0,
          'image_category_icon' => 0,
          'image_custom_crop' => 0,
          'image_large' => 0,
          'image_linkit_thumb' => 0,
          'image_medium' => 0,
          'image_thumbnail' => 0,
          'image_thumbnail_crop' => 0,
          'image_thumbnail_large' => 0,
          'image_thumbnail_small' => 0,
          'image_widescreen_crop' => 0,
          'image_widescreen_large' => 0,
          'image_widescreen_medium' => 0,
          'image_widescreen_small' => 0,
          'link' => 0,
        ),
        'insert_width' => '',
        'manualcrop_crop_info' => 1,
        'manualcrop_default_crop_area' => 1,
        'manualcrop_enable' => 1,
        'manualcrop_filter_insert' => 0,
        'manualcrop_inline_crop' => 0,
        'manualcrop_instant_crop' => 0,
        'manualcrop_instant_preview' => 1,
        'manualcrop_keyboard' => 1,
        'manualcrop_maximize_default_crop_area' => 0,
        'manualcrop_require_cropping' => array(
          'widescreen_crop' => 'widescreen_crop',
        ),
        'manualcrop_styles_list' => array(
          'widescreen_crop' => 'widescreen_crop',
        ),
        'manualcrop_styles_mode' => 'include',
        'manualcrop_thumblist' => 1,
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 2,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Gallery Images');

  return $field_instances;
}
