<?php

/**
 * Implements hook_menu().
 */
function ucla_data_registry_helper_menu() {
  $items['app/data-registry'] = array(
    'page callback' => 'ucla_data_registry_helper_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function ucla_data_registry_helper_page() {
  $GLOBALS['conf']['cache'] = FALSE; // keep pages out of cache for Shibboleth to work
  $shib_logout = variable_get('shib_auth_full_logout_url');

  // Blob of HTML to display on page
  $output = '
    <h2>Data Registry&nbsp;</h2>
    <p><a href="/app/data-registry/add">Add Data Registry Content</a></p>
    <p><a href="/app/data-registry/update-registry">View or Edit Your Data Registry Entries</a>
    </p><p>&nbsp;</p><h2>Shibboleth Logout</h2>
    <p><a href="' . $shib_logout . '" target="_blank">Shibboleth Logout</a></p>
    <p>Use the above link to log out of your Shibboleth session.&nbsp;</p>
    <p>&nbsp;</p><p>&nbsp;</p>
  ';
 
  return $output;
}

