<?php

/**
 * @file
 * Main code file for uclalib_opening_hours module.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function uclalib_opening_hours_ctools_plugin_api($module, $api) {
  switch ("$module:$api") {
    default:
      return array('version' => '1');
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function uclalib_opening_hours_ctools_plugin_directory($owner, $plugin_type) {
  switch ("$owner:$plugin_type") {
    case 'ctools:content_types':
      return "plugins/$owner/$plugin_type";
  }

  return NULL;
}

/**
 * Abbreviate a time string to the required format.
 *
 * @param $time
 *   The time as 'HH:MM:SS';
 * @return string
 *   The time with the abbreviated form. Ex: 2p, 12:30a
 */
function _uclalib_opening_hours_short_time($time) {
  $matches = array();

  if (preg_match('/^([0-9]{2}):([0-9]{2}):([0-9]{2})$/', $time, $matches)) {
    $hour = $matches[1];
    $minute = $matches[2];

    $ap = 'a';
    if ($hour > 12) {
      $hour = $hour - 12;
      $ap = 'p';
    }

    $time = $hour;

    if ($minute != '00') {
      $time .= ':' . $minute;
    }

    $time .= $ap;
  }

  return $time;
}