<?php

function statsform_menu() {
  $items = array();
  
  $items['statsform/form'] = array(
    'title' => 'Stats Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('statsform_page_one'),
    'access callback' => TRUE,
    'description' => 'For statsform use',
  );
  $items['statsform/references'] = array(
    'title' => 'Stats Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('statsform_references'),
    'access callback' => TRUE,
    'description' => 'For statsform use',
  );
  $items['statsform/mockup'] = array(
    'title' => 'Stats Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('statsform_mockup'),
    'access callback' => TRUE,
    'description' => 'For statsform use',
  );
 
 
  return $items;
}

/**
 * Implements hook_theme().
 */
function statsform_theme($existing, $type, $theme, $path) {
    return array(
        'hijack' => array(
            'template' => 'page--hijacked',
            'render element' => 'page',
            'path' => drupal_get_path('module', 'statsform') . '/templates',
            ),
    );
}

/**
 * Implements hook_page_alter().
 */
function statsform_page_alter(&$page) {
    $page['#theme'] = 'hijack';
}

$biomed_desks = array(
    "1" => "Circulation Desk",
    "2" => "Reference Desk",
    "3" => "Information Desk",
    "4" => "Off-Desk",
);

$powell_desks = array(
    "1" => "Circulation Desk: second floor counter",
    "2" => "Reference Desk",
    "3" => "Information Desk",
    "4" => "Off-Desk",
    "5" => "Circulation Desk: entrance foyer",
    "6" => "Rovers",
);

$yrl_desks = array(
    "1" => "Circulation Desk",
    "2" => "A Level Service Desk",
    "3" => "Information Desk",
    "4" => "Cashier Window",
    "5" => "Phone answering station",
);

$arts_desks = array(
    "1" => "Circulation Desk",
    "2" => "Reference Desk",
    "3" => "Off-Desk",
);

$music_desks = array(
    "1" => "Circulation Desk",
    "2" => "Reference Desk",
    "3" => "Off-Desk",
);



/**
* page 1 - Welcome ......................................................................................................................
* page 1 - Welcome ......................................................................................................................
* page 1 - Welcome ......................................................................................................................
 */

function statsform_page_one($form, &$form_state) {



  // Jump to appropriate page if necessary
  // Jump to appropriate page if necessary
  // Jump to appropriate page if necessary

  // Display page 2 if $form_state['page_num'] == 2
  if (!empty($form_state['page_num']) && $form_state['page_num'] == 2) {
    //print_r('page_2');
    return statsform_page_two($form, $form_state);
  }
  elseif (!empty($form_state['page_num']) && $form_state['page_num'] == 3) {
    //print_r('page_3');
    return statsform_page_three($form, $form_state);
  }
  elseif (!empty($form_state['page_num']) && $form_state['page_num'] == 4) {
    //print_r('page_4a');
    return statsform_page_four($form, $form_state);
  }
  elseif (!empty($form_state['page_num']) && $form_state['page_num'] == 5) {
    //print_r('page_5');
    return statsform_page_five($form, $form_state);
  }
  elseif (!empty($form_state['page_num']) && $form_state['page_num'] == 6) {
    //print_r('page_6');
    return statsform_page_six($form, $form_state);
  }
  elseif (!empty($form_state['page_num']) && $form_state['page_num'] == 7) {
    //print_r('page_7');
    return statsform_page_seven($form, $form_state);
  }

$form['home'] = array(
        '#type' => 'item',
        '#submit' => array('rc_res_form_page_one_handler_submit'),
        '#markup' => '
        
<html>
    <head>
        <title>Stats Redesign Project</title>

        <!-- JQuery -->
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js"></script>

        <!-- Semantic UI -->
        <link rel="stylesheet" type="text/css" href="../semantic/semantic.min.css">
        <script src="../semantic/semantic.min.js"></script>

        <!-- Personally Defined CSS/Javascript -->
        <link rel="stylesheet" type="text/css" href="../css/stylesheet.css">


        <!-- Google Font Montserrat --> 

        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">   


    </head>
    <body>

        <!-- Menu -->
        <div class="ui secondary inverted menu">
            <div class="ui huge breadcrumb">
                <div class="active section" >
                    <a class="item">
                        Home
                    </a>
                </div>
            </div>
            <div class="right menu">
                <a class="item">
                    Login
                </a>
            </div>
        </div>

        <!-- Content -->
      <div class="ui equal width height center aligned grid">
         <div class="row">
          <a class="six wide column" onclick="myfunction1()" id="YRL"> <div class="verticalalign"> YOUNG RESEARCH LIBRARY</div></a>
          <div class="four wide column">
            <img class ="img-responsive" src="../img/Statsform_Stock_Photos/powellnight.jpg">
        </div>
        <a class="six wide column" href="#" onclick="myfunction2()" id="BL"> <div class="verticalalign"> BIOMEDICAL LIBRARY </div> </a>
    </div>

    <div class="row">
        <div class="four wide column"> <div align="left">
           <img class ="img-responsive" src="../img/Statsform_Stock_Photos/powellstudent.jpg"></div>
       </div>
       <a class="seven wide column" href="#" onclick="myfunction3()" id = "POWELL"> <div class="verticalalign">POWELL LIBRARY</div></a> 
       <div class="five wide column">
        <img class ="img-responsive" src="../img/Statsform_Stock_Photos/clicc.jpg"></div>
    </div>


    <div class="row">
        <div class="four wide column">
            <img class ="img-responsive" src="../img/Statsform_Stock_Photos/books.jpg">
        </div>
        <a class="four wide column" href="#" onclick="myfunction4()" id="AL"><div class="verticalalign"> ARTS LIBRARY</div></a>
        <div class="four wide column">
            <img class ="img-responsive" src="../img/Statsform_Stock_Photos/DAY3_SHOT5_YOUNGLIBRARY-2192_r_cmyk.jpg">
        </div>
        <a class="four wide column" href="#" onclick="myfunction5()" id="ML"><div class="verticalalign">MUSIC LIBRARY</div></a>
    </div>
</div>  
</body>


<script>
function myfunction1() {
    document.getElementById("edit-bid").value = "YRL";
    document.getElementById("statsform-page-one").submit();
}
function myfunction2() {
    document.getElementById("edit-bid").value = "BIOMEDICAL";
    document.getElementById("statsform-page-one").submit();
}
function myfunction3() {
    document.getElementById("edit-bid").value = "POWELL";
    document.getElementById("statsform-page-one").submit();
}
function myfunction4() {
    document.getElementById("edit-bid").value = "ARTS";
    document.getElementById("statsform-page-one").submit();
}
function myfunction5() {
    document.getElementById("edit-bid").value = "MUSIC";
    document.getElementById("statsform-page-one").submit();
}
</script>

</html>
        ',
    
        );
    
    


  $form['bid'] = array(
    '#type' => 'textfield', 
    '#default_value' => $bid
    );
 

  $form['submit'] = array(
    '#type'  => 'submit',
    '#value' => t('Start'),
    '#submit' => array('statsform_page_one_handler_submit'),
  );
  return $form;
}


/**
* page 2 - Welcome ......................................................................................................................
* page 2 - Welcome ......................................................................................................................
* page 2 - Welcome ......................................................................................................................
 */

function statsform_page_two($form, &$form_state) {

  // build form for page
  //  $form_state['page_num'] = 1;
  
  krumo($form_state['values']['bid']);
  $library = $form_state['values']['bid'];
  statsform_session_variable_set('statsform', 'libraryName', $library);
  statsform_session_variable_get('statsform', 'libraryName');
 
 
  if ($library == 'POWELL'){
    statsform_session_variable_set('statsform', 'pos1', 'Circulation Desk: second floor counter');
    statsform_session_variable_set('statsform', 'pos2', 'Reference Desk');
    statsform_session_variable_set('statsform', 'pos3', 'Information Desk');
    statsform_session_variable_set('statsform', 'pos4', 'Off-Desk');
    statsform_session_variable_set('statsform', 'pos5', 'Circulation Desk: entrance foyer');
    statsform_session_variable_set('statsform', 'pos6', 'Rovers');
  }
  
  print statsform_session_variable_get('statsform', 'pos1');
  print statsform_session_variable_get('statsform', 'pos2');
  print statsform_session_variable_get('statsform', 'pos3');
  print statsform_session_variable_get('statsform', 'pos4');
  print statsform_session_variable_get('statsform', 'pos5');
  print statsform_session_variable_get('statsform', 'pos6');


  $form = array();



$form['ref'] = array(
        '#type' => 'item',
        '#markup' => '
        
<html>
<head>
    <title>Stats Redesign Project</title>

    <!-- Semantic UI -->
    <link rel="stylesheet" type="text/css" href="../assets/includes/semantic.min.css">
    <script type="text/javascript" src="../assets/includes/semantic.min.js"></script>

    <!-- JQuery -->
    <script type="text/javascript" src="../assets/includes/jquery.min.js"></script>

    <!-- Customization -->
    <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
    <!-- IScroll Link here -->
    <script type="text/javascript" src="../css/stylesheet.css"></script>
</head>
<body>

    <!-- Menu -->
    <div class="ui secondary inverted menu">
        <div class="ui huge breadcrumb">
            <div class="section" >
                <a class="item" href="index.html">
                    Home
                </a>
            </div>
            <i class="right chevron icon divider"></i>
            ');
  $form['ref1'] = array(
        '#type' => 'item',
        '#prefix' => '
            <div class="active section">
                <a class="item">',
        '#markup' =>t(ucfirst(statsform_session_variable_get('statsform', 'libraryName')).' 
                </a>
            </div>
        </div>
        <div class="right menu">
            <a class="item">
                Login
            </a>
        </div>
    </div>

    <!-- Content -->


    <div class="ui equal width center aligned grid">

<div class = "eight wide column" id="sec1"  >
 <a href = "mockup" > 
    <div class="containerBox">
    <div class="text-box">
        <h4>TAP</h4>
    </div>
    <img src="../img/Statsform_Stock_Photos/powellnight.jpg"/>
</div>
</a>
</div>'));

$form['pos2'] = array(
        '#type' => 'item',
        '#prefix' => ' <div class="ui equal width center aligned grid"><a href = "mockup"class="eight wide column" id="sec2"> <div class="verticalalign">',
        '#markup' => t(ucfirst(statsform_session_variable_get('statsform', 'pos2')).' </div></a></div>'));
        
$form['pos3'] = array(
        '#type' => 'item',
        '#prefix' => '<a href = "mockup"class="eight wide column" id="sec3"> <div class="verticalalign">',
        '#markup' => t(ucfirst(statsform_session_variable_get('statsform', 'pos3')).' </div></a>'));

$form['pos4'] = array(
        '#type' => 'item',
        '#prefix' => '<a href = "mockup"class="eight wide column" id="sec4"> <div class="verticalalign">',
        '#markup' => t(ucfirst(statsform_session_variable_get('statsform', 'pos4')).' </div></a>'));

$form['pos5'] = array(
        '#type' => 'item',
        '#prefix' => '<a href = "mockup"class="eight wide column" id="sec5"> <div class="verticalalign">',
        '#markup' => t(ucfirst(statsform_session_variable_get('statsform', 'pos5')).' </div></a>'));

$form['pos6'] = array(
        '#type' => 'item',
        '#prefix' => '<a href = "mockup"class="eight wide column" id="sec6"> <div class="verticalalign">',
        '#markup' => t(ucfirst(statsform_session_variable_get('statsform', 'pos6')).' </div></a>

      
    </div>    


<!-- <div class="containerBox">
    <div class="text-box">
        <h4>Your Text is responsive and centered</h4>
    </div>
    <img class="img-responsive" src="http://placehold.it/900x100"/>
</div>
 
 ** Attempted to create hyperlink photo with text on top. 3/1
!-->

</body>


</html>
        
        ')
        
    );

  $form['next'] = array(
    '#type'  => 'submit',
    '#value' => t('Start'),
    '#submit' => array('statsform_page_one_handler_submit'),
  );
  return $form;
}


/**
 * Page 1 submit handler.
 * Page 1 submit handler.
 * Page 1 submit handler.
 *
 * Save the vals from page one for a later final submit.
 */
  // Values are saved for each page.
  // to carry forward to subsequent pages in the form.
  // The Forms API rebuilds the form.
function statsform_page_one_handler_submit($form, &$form_state) {
  $form_state['page_values'][1] = $form_state['values'];

  // set page num if it does not yet exist, ie this is the first pass
  if (empty($form_state['page_num'])) { $form_state['page_num'] = 1; } 

  // go forward to page 2
  $form_state['page_num'] = 2;

  $form_state['rebuild'] = TRUE;
}

   
  








/**
 * session variable functions
 * session variable functions
 * session variable functions
 *
 * Based on code from Peter Moulding http://petermoulding.com/session_variable
 */
function statsform_session_variable_check_session()
	{
	return session_id() != '';
	}

function statsform_session_variable_check_module($module4rc)
	{
	$module_safe4rc = statsform_session_variable_safe($module4rc);
	if($module_safe4rc !== $module4rc or isset($_SESSION[$module4rc]))
		{
		return false;
		}
	return true;
	}

function statsform_session_variable_delete($module4rc, $name4rc)
	{
	if(statsform_session_variable_is($module4rc, $name4rc))
		{
		$module4rc = statsform_session_variable_safe($module4rc);
		$name4rc = statsform_session_variable_safe($name4rc);
		unset($_SESSION[$module4rc][$name4rc]);
		if(!count($_SESSION[$module4rc]))
			{
			unset($_SESSION[$module4rc]);
			}
		return true;
		}
	return false;
	}

function statsform_session_variable_is($module4rc, $name4rc)
	{
	$module4rc = statsform_session_variable_safe($module4rc);
	$name4rc = statsform_session_variable_safe($name4rc);
	return (isset($_SESSION[$module4rc]) and isset($_SESSION[$module4rc][$name4rc]));
	}

function statsform_session_variable_get($module4rc, $name4rc, $default_value = '')
	{
	if(rc_session_variable_is($module4rc, $name4rc))
		{
		$module4rc = statsform_session_variable_safe($module4rc);
		$name4rc = statsform_session_variable_safe($name4rc);
		return $_SESSION[$module4rc][$name4rc];
		}
	return $default_value;
	}

function statsform_session_variable_set($module4rc, $name4rc, $value = '')
	{
	$module4rc = statsform_session_variable_safe($module4rc);
	$name4rc = statsform_session_variable_safe($name4rc);
	$_SESSION[$module4rc][$name4rc] = $value;
	}

/*
Is the module name or the variable name safe for use as an entry in the session?
This function returns a safe version of the name.
*/
function statsform_session_variable_safe($name4rc = '')
	{
	return htmlentities($name4rc);
	}
