<?php
/**
 * @file
 * uclalib_search.views_default.inc
 */

/**
 * Implements hook_views_default_views().
 */
function uclalib_search_views_default_views() {
  $export = array();

  $view = new view();
  $view->name = 'content_search';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'search_api_index_site_general_search';
  $view->human_name = 'Content Search';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Site Search';
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'none';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['row_plugin'] = 'fields';
  /* Field: Indexed Content: Node ID */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nid']['separator'] = '';
  $handler->display->display_options['fields']['nid']['link_to_entity'] = 0;
  /* Field: Indexed Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_entity'] = 1;
  /* Field: Search: Excerpt */
  $handler->display->display_options['fields']['search_api_excerpt']['id'] = 'search_api_excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['search_api_excerpt']['field'] = 'search_api_excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['label'] = '';
  $handler->display->display_options['fields']['search_api_excerpt']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['search_api_excerpt']['link_to_entity'] = 0;
  /* Sort criterion: Search: Relevance */
  $handler->display->display_options['sorts']['search_api_relevance']['id'] = 'search_api_relevance';
  $handler->display->display_options['sorts']['search_api_relevance']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['sorts']['search_api_relevance']['field'] = 'search_api_relevance';
  $handler->display->display_options['sorts']['search_api_relevance']['order'] = 'DESC';
  /* Filter criterion: Search: Fulltext search */
  $handler->display->display_options['filters']['search_api_views_fulltext']['id'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['filters']['search_api_views_fulltext']['field'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['exposed'] = TRUE;
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator_id'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['label'] = 'Search';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['identifier'] = 'search_query';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['required'] = TRUE;
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  $handler->display->display_options['filters']['search_api_views_fulltext']['min_length'] = '3';

  /* Display: Page */
  $handler = $view->new_display('page', 'Page', 'page');
  $handler->display->display_options['path'] = 'site-search-old';
  $export['content_search'] = $view;

  $view = new view();
  $view->name = 'location_search';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'search_api_index_location_search';
  $view->human_name = 'Location Search';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'none';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['pager']['options']['id'] = '0';
  $handler->display->display_options['pager']['options']['quantity'] = '9';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['row_plugin'] = 'entity';
  $handler->display->display_options['row_options']['view_mode'] = 'teaser';
  /* No results behavior: Global: Text area */
  $handler->display->display_options['empty']['area']['id'] = 'area';
  $handler->display->display_options['empty']['area']['table'] = 'views';
  $handler->display->display_options['empty']['area']['field'] = 'area';
  $handler->display->display_options['empty']['area']['empty'] = TRUE;
  $handler->display->display_options['empty']['area']['content'] = 'No results found for this search.';
  $handler->display->display_options['empty']['area']['format'] = 'full_html';
  /* Field: Indexed Content: Node ID */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'search_api_index_location_search';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nid']['separator'] = '';
  $handler->display->display_options['fields']['nid']['link_to_entity'] = 0;
  /* Field: Indexed Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'search_api_index_location_search';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_entity'] = 1;
  /* Sort criterion: Indexed Content: Queue position */
  $handler->display->display_options['sorts']['queue_position']['id'] = 'queue_position';
  $handler->display->display_options['sorts']['queue_position']['table'] = 'search_api_index_location_search';
  $handler->display->display_options['sorts']['queue_position']['field'] = 'queue_position';
  /* Sort criterion: Search: Relevance */
  $handler->display->display_options['sorts']['search_api_relevance']['id'] = 'search_api_relevance';
  $handler->display->display_options['sorts']['search_api_relevance']['table'] = 'search_api_index_location_search';
  $handler->display->display_options['sorts']['search_api_relevance']['field'] = 'search_api_relevance';
  $handler->display->display_options['sorts']['search_api_relevance']['order'] = 'DESC';
  /* Filter criterion: Search: Fulltext search */
  $handler->display->display_options['filters']['search_api_views_fulltext']['id'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['table'] = 'search_api_index_location_search';
  $handler->display->display_options['filters']['search_api_views_fulltext']['field'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['exposed'] = TRUE;
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator_id'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['identifier'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  $handler->display->display_options['filters']['search_api_views_fulltext']['fields'] = array(
    'title' => 'title',
    'field_location_nickname' => 'field_location_nickname',
    'field_location_alt_names' => 'field_location_alt_names',
  );
  /* Filter criterion: Opening hours: Open Now */
  $handler->display->display_options['filters']['open_now']['id'] = 'open_now';
  $handler->display->display_options['filters']['open_now']['table'] = 'search_api_index_location_search';
  $handler->display->display_options['filters']['open_now']['field'] = 'open_now';
  $handler->display->display_options['filters']['open_now']['value'] = 0;
  $handler->display->display_options['filters']['open_now']['exposed'] = TRUE;
  $handler->display->display_options['filters']['open_now']['expose']['operator_id'] = '';
  $handler->display->display_options['filters']['open_now']['expose']['label'] = 'Open Now';
  $handler->display->display_options['filters']['open_now']['expose']['operator'] = 'open_now_op';
  $handler->display->display_options['filters']['open_now']['expose']['identifier'] = 'open_now';
  $handler->display->display_options['filters']['open_now']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
    4 => 0,
    5 => 0,
  );

  /* Display: Content pane */
  $handler = $view->new_display('panel_pane', 'Content pane', 'panel_pane_1');
  $handler->display->display_options['exposed_block'] = TRUE;
  $handler->display->display_options['allow']['use_pager'] = 0;
  $handler->display->display_options['allow']['items_per_page'] = 0;
  $handler->display->display_options['allow']['offset'] = 0;
  $handler->display->display_options['allow']['link_to_view'] = 0;
  $handler->display->display_options['allow']['more_link'] = 0;
  $handler->display->display_options['allow']['path_override'] = 0;
  $handler->display->display_options['allow']['title_override'] = 'title_override';
  $handler->display->display_options['allow']['exposed_form'] = 0;
  $handler->display->display_options['allow']['fields_override'] = 0;
  $handler->display->display_options['inherit_panels_path'] = '1';

  /* Display: Open Now */
  $handler = $view->new_display('page', 'Open Now', 'page_1');
  $handler->display->display_options['defaults']['pager'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'none';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['defaults']['style_plugin'] = FALSE;
  $handler->display->display_options['style_plugin'] = 'views_json';
  $handler->display->display_options['style_options']['plaintext_output'] = 1;
  $handler->display->display_options['style_options']['remove_newlines'] = 0;
  $handler->display->display_options['style_options']['jsonp_prefix'] = '';
  $handler->display->display_options['style_options']['using_views_api_mode'] = 0;
  $handler->display->display_options['style_options']['object_arrays'] = 0;
  $handler->display->display_options['style_options']['numeric_strings'] = 0;
  $handler->display->display_options['style_options']['bigint_string'] = 0;
  $handler->display->display_options['style_options']['pretty_print'] = 0;
  $handler->display->display_options['style_options']['unescaped_slashes'] = 0;
  $handler->display->display_options['style_options']['unescaped_unicode'] = 0;
  $handler->display->display_options['style_options']['char_encoding'] = array();
  $handler->display->display_options['defaults']['style_options'] = FALSE;
  $handler->display->display_options['defaults']['row_plugin'] = FALSE;
  $handler->display->display_options['defaults']['row_options'] = FALSE;
  $handler->display->display_options['defaults']['empty'] = FALSE;
  /* No results behavior: Global: Text area */
  $handler->display->display_options['empty']['area']['id'] = 'area';
  $handler->display->display_options['empty']['area']['table'] = 'views';
  $handler->display->display_options['empty']['area']['field'] = 'area';
  $handler->display->display_options['empty']['area']['empty'] = TRUE;
  $handler->display->display_options['empty']['area']['content'] = '<span class="location-closed">Closed</span>';
  $handler->display->display_options['empty']['area']['format'] = 'full_html';
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Indexed Content: Node ID */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'search_api_index_location_search';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['alter']['text'] = '<span class="location-open-now">Open Now</span>';
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nid']['separator'] = '';
  $handler->display->display_options['fields']['nid']['link_to_entity'] = 0;
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  /* Contextual filter: Indexed Content: Node ID */
  $handler->display->display_options['arguments']['nid']['id'] = 'nid';
  $handler->display->display_options['arguments']['nid']['table'] = 'search_api_index_location_search';
  $handler->display->display_options['arguments']['nid']['field'] = 'nid';
  $handler->display->display_options['arguments']['nid']['default_action'] = 'empty';
  $handler->display->display_options['arguments']['nid']['default_argument_type'] = 'fixed';
  $handler->display->display_options['arguments']['nid']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['nid']['break_phrase'] = 0;
  $handler->display->display_options['arguments']['nid']['not'] = 0;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Opening hours: Open Now */
  $handler->display->display_options['filters']['open_now']['id'] = 'open_now';
  $handler->display->display_options['filters']['open_now']['table'] = 'search_api_index_location_search';
  $handler->display->display_options['filters']['open_now']['field'] = 'open_now';
  $handler->display->display_options['filters']['open_now']['value'] = 1;
  $handler->display->display_options['filters']['open_now']['expose']['operator_id'] = '';
  $handler->display->display_options['filters']['open_now']['expose']['label'] = 'Open Now';
  $handler->display->display_options['filters']['open_now']['expose']['operator'] = 'open_now_op';
  $handler->display->display_options['filters']['open_now']['expose']['identifier'] = 'open_now';
  $handler->display->display_options['filters']['open_now']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  $handler->display->display_options['path'] = 'ajax/open_now/%';
  $export['location_search'] = $view;

  $view = new view();
  $view->name = 'news_search';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'search_api_index_site_general_search';
  $view->human_name = 'News Search';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'none';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['exposed_form']['options']['reset_button'] = TRUE;
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['pager']['options']['items_per_page'] = '20';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['pager']['options']['id'] = '0';
  $handler->display->display_options['pager']['options']['quantity'] = '9';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['style_options']['row_class'] = 'news-teaser news-teaser--with-thumbnail';
  $handler->display->display_options['style_options']['default_row_class'] = FALSE;
  $handler->display->display_options['style_options']['row_class_special'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  /* No results behavior: Global: Text area */
  $handler->display->display_options['empty']['area']['id'] = 'area';
  $handler->display->display_options['empty']['area']['table'] = 'views';
  $handler->display->display_options['empty']['area']['field'] = 'area';
  $handler->display->display_options['empty']['area']['empty'] = TRUE;
  $handler->display->display_options['empty']['area']['content'] = 'No results found for this search.';
  $handler->display->display_options['empty']['area']['format'] = 'full_html';
  /* Field: Indexed Content: Node ID */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nid']['link_to_entity'] = 0;
  /* Field: Indexed Content: Exhibition Thumbnail */
  $handler->display->display_options['fields']['field_event_thumbnail']['id'] = 'field_event_thumbnail';
  $handler->display->display_options['fields']['field_event_thumbnail']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_event_thumbnail']['field'] = 'field_event_thumbnail';
  $handler->display->display_options['fields']['field_event_thumbnail']['label'] = '';
  $handler->display->display_options['fields']['field_event_thumbnail']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_event_thumbnail']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_event_thumbnail']['settings'] = array(
    'image_style' => 'thumbnail_small',
    'image_link' => 'content',
  );
  /* Field: Indexed Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_entity'] = 1;
  /* Field: The main body text: Summary (indexed) */
  $handler->display->display_options['fields']['body_summary']['id'] = 'body_summary';
  $handler->display->display_options['fields']['body_summary']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['body_summary']['field'] = 'body_summary';
  $handler->display->display_options['fields']['body_summary']['label'] = '';
  $handler->display->display_options['fields']['body_summary']['exclude'] = TRUE;
  $handler->display->display_options['fields']['body_summary']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['body_summary']['link_to_entity'] = 0;
  /* Field: Global: Custom text */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['alter']['text'] = '<div><h3>[title]</h3></div>
<div><p>[body_summary]</p></div>';
  $handler->display->display_options['fields']['nothing']['element_type'] = '0';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  /* Sort criterion: Indexed Content: Date created */
  $handler->display->display_options['sorts']['created']['id'] = 'created';
  $handler->display->display_options['sorts']['created']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['sorts']['created']['field'] = 'created';
  $handler->display->display_options['sorts']['created']['order'] = 'DESC';
  /* Filter criterion: Indexed Content: Content type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'news' => 'news',
  );
  /* Filter criterion: Search: Fulltext search */
  $handler->display->display_options['filters']['search_api_views_fulltext']['id'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['filters']['search_api_views_fulltext']['field'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['exposed'] = TRUE;
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator_id'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['label'] = 'Search';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['identifier'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );

  /* Display: News Search */
  $handler = $view->new_display('panel_pane', 'News Search', 'news_search');
  $handler->display->display_options['exposed_block'] = TRUE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Indexed Content: Node ID */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nid']['link_to_entity'] = 0;
  /* Field: Indexed Content: URL */
  $handler->display->display_options['fields']['url']['id'] = 'url';
  $handler->display->display_options['fields']['url']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['url']['field'] = 'url';
  $handler->display->display_options['fields']['url']['label'] = '';
  $handler->display->display_options['fields']['url']['exclude'] = TRUE;
  $handler->display->display_options['fields']['url']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['url']['display_as_link'] = FALSE;
  $handler->display->display_options['fields']['url']['link_to_entity'] = 0;
  /* Field: Indexed Content: Exhibition Thumbnail */
  $handler->display->display_options['fields']['field_event_thumbnail']['id'] = 'field_event_thumbnail';
  $handler->display->display_options['fields']['field_event_thumbnail']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_event_thumbnail']['field'] = 'field_event_thumbnail';
  $handler->display->display_options['fields']['field_event_thumbnail']['label'] = '';
  $handler->display->display_options['fields']['field_event_thumbnail']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_event_thumbnail']['element_wrapper_class'] = 'news-teaser__thumbnail';
  $handler->display->display_options['fields']['field_event_thumbnail']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['field_event_thumbnail']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_event_thumbnail']['settings'] = array(
    'image_style' => 'widescreen_medium',
    'image_link' => 'content',
  );
  /* Field: Indexed Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_entity'] = 1;
  /* Field: Indexed Content: The main body text */
  $handler->display->display_options['fields']['body']['id'] = 'body';
  $handler->display->display_options['fields']['body']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['body']['field'] = 'body';
  $handler->display->display_options['fields']['body']['label'] = '';
  $handler->display->display_options['fields']['body']['exclude'] = TRUE;
  $handler->display->display_options['fields']['body']['alter']['trim_whitespace'] = TRUE;
  $handler->display->display_options['fields']['body']['alter']['max_length'] = '140';
  $handler->display->display_options['fields']['body']['alter']['more_link'] = TRUE;
  $handler->display->display_options['fields']['body']['alter']['more_link_text'] = 'more';
  $handler->display->display_options['fields']['body']['alter']['more_link_path'] = '[url]';
  $handler->display->display_options['fields']['body']['alter']['strip_tags'] = TRUE;
  $handler->display->display_options['fields']['body']['alter']['trim'] = TRUE;
  $handler->display->display_options['fields']['body']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['body']['settings'] = array(
    'trim_length' => '300',
  );
  /* Field: Global: Custom text */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['alter']['text'] = '<div class="news-teaser__title">[title]</div>
<div class="news-teaser__description">[body]</div>';
  $handler->display->display_options['fields']['nothing']['element_type'] = '0';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nothing']['element_wrapper_class'] = 'news-teaser__text-wrapper';
  $handler->display->display_options['fields']['nothing']['element_default_classes'] = FALSE;
  $handler->display->display_options['allow']['use_pager'] = 0;
  $handler->display->display_options['allow']['items_per_page'] = 0;
  $handler->display->display_options['allow']['offset'] = 0;
  $handler->display->display_options['allow']['link_to_view'] = 0;
  $handler->display->display_options['allow']['more_link'] = 0;
  $handler->display->display_options['allow']['path_override'] = 'path_override';
  $handler->display->display_options['allow']['title_override'] = 'title_override';
  $handler->display->display_options['allow']['exposed_form'] = 0;
  $handler->display->display_options['allow']['fields_override'] = 0;
  $handler->display->display_options['inherit_panels_path'] = '1';
  $export['news_search'] = $view;

  $view = new view();
  $view->name = 'site_multi_search';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'search_api_multi';
  $view->human_name = 'Site Multi Search';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Site Search';
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'none';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['exposed_form']['options']['submit_button'] = 'Search';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['row_plugin'] = 'fields';
  /* Field: Search: Page manager pages results */
  $handler->display->display_options['fields']['page_manager_pages']['id'] = 'page_manager_pages';
  $handler->display->display_options['fields']['page_manager_pages']['table'] = 'search_api_multi';
  $handler->display->display_options['fields']['page_manager_pages']['field'] = 'page_manager_pages';
  $handler->display->display_options['fields']['page_manager_pages']['exclude'] = TRUE;
  $handler->display->display_options['fields']['page_manager_pages']['link_to_entity'] = 1;
  $handler->display->display_options['fields']['page_manager_pages']['display'] = 'view';
  $handler->display->display_options['fields']['page_manager_pages']['bypass_access'] = 0;
  /* Field: Search: Site General Search results */
  $handler->display->display_options['fields']['site_general_search']['id'] = 'site_general_search';
  $handler->display->display_options['fields']['site_general_search']['table'] = 'search_api_multi';
  $handler->display->display_options['fields']['site_general_search']['field'] = 'site_general_search';
  $handler->display->display_options['fields']['site_general_search']['exclude'] = TRUE;
  $handler->display->display_options['fields']['site_general_search']['link_to_entity'] = 1;
  $handler->display->display_options['fields']['site_general_search']['display'] = 'view';
  $handler->display->display_options['fields']['site_general_search']['view_mode'] = 'teaser';
  $handler->display->display_options['fields']['site_general_search']['bypass_access'] = 0;
  /* Field: Page manager pages: Title (indexed) */
  $handler->display->display_options['fields']['page_manager_pages_title']['id'] = 'page_manager_pages_title';
  $handler->display->display_options['fields']['page_manager_pages_title']['table'] = 'search_api_multi';
  $handler->display->display_options['fields']['page_manager_pages_title']['field'] = 'page_manager_pages_title';
  $handler->display->display_options['fields']['page_manager_pages_title']['label'] = '';
  $handler->display->display_options['fields']['page_manager_pages_title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['page_manager_pages_title']['link_to_entity'] = 1;
  /* Field: Site General Search: Title (indexed) */
  $handler->display->display_options['fields']['site_general_search_title']['id'] = 'site_general_search_title';
  $handler->display->display_options['fields']['site_general_search_title']['table'] = 'search_api_multi';
  $handler->display->display_options['fields']['site_general_search_title']['field'] = 'site_general_search_title';
  $handler->display->display_options['fields']['site_general_search_title']['label'] = '';
  $handler->display->display_options['fields']['site_general_search_title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['site_general_search_title']['link_to_entity'] = 1;
  /* Field: Search: Excerpt */
  $handler->display->display_options['fields']['search_api_excerpt']['id'] = 'search_api_excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['table'] = 'search_api_multi';
  $handler->display->display_options['fields']['search_api_excerpt']['field'] = 'search_api_excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['label'] = '';
  $handler->display->display_options['fields']['search_api_excerpt']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['search_api_excerpt']['link_to_entity'] = 0;
  /* Sort criterion: Search: Relevance */
  $handler->display->display_options['sorts']['search_api_relevance']['id'] = 'search_api_relevance';
  $handler->display->display_options['sorts']['search_api_relevance']['table'] = 'search_api_multi';
  $handler->display->display_options['sorts']['search_api_relevance']['field'] = 'search_api_relevance';
  $handler->display->display_options['sorts']['search_api_relevance']['order'] = 'DESC';
  /* Filter criterion: Search: Index */
  $handler->display->display_options['filters']['search_api_multi_index']['id'] = 'search_api_multi_index';
  $handler->display->display_options['filters']['search_api_multi_index']['table'] = 'search_api_multi';
  $handler->display->display_options['filters']['search_api_multi_index']['field'] = 'search_api_multi_index';
  $handler->display->display_options['filters']['search_api_multi_index']['value'] = array(
    'site_general_search' => 'site_general_search',
    'page_manager_pages' => 'page_manager_pages',
  );
  /* Filter criterion: Search: Fulltext search */
  $handler->display->display_options['filters']['search_api_multi_fulltext']['id'] = 'search_api_multi_fulltext';
  $handler->display->display_options['filters']['search_api_multi_fulltext']['table'] = 'search_api_multi';
  $handler->display->display_options['filters']['search_api_multi_fulltext']['field'] = 'search_api_multi_fulltext';
  $handler->display->display_options['filters']['search_api_multi_fulltext']['exposed'] = TRUE;
  $handler->display->display_options['filters']['search_api_multi_fulltext']['expose']['operator_id'] = 'search_api_multi_fulltext_op';
  $handler->display->display_options['filters']['search_api_multi_fulltext']['expose']['label'] = 'Search';
  $handler->display->display_options['filters']['search_api_multi_fulltext']['expose']['operator'] = 'search_api_multi_fulltext_op';
  $handler->display->display_options['filters']['search_api_multi_fulltext']['expose']['identifier'] = 'search_query';
  $handler->display->display_options['filters']['search_api_multi_fulltext']['expose']['required'] = TRUE;
  $handler->display->display_options['filters']['search_api_multi_fulltext']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
    4 => 0,
    5 => 0,
    6 => 0,
    7 => 0,
  );
  $handler->display->display_options['filters']['search_api_multi_fulltext']['fields'] = array(
    'site_general_search:title' => 'site_general_search:title',
    'site_general_search:field_address' => 'site_general_search:field_address',
    'site_general_search:field_location_alt_names' => 'site_general_search:field_location_alt_names',
    'site_general_search:field_location_building' => 'site_general_search:field_location_building',
    'site_general_search:field_location_email' => 'site_general_search:field_location_email',
    'site_general_search:field_location_nickname' => 'site_general_search:field_location_nickname',
    'site_general_search:field_location_phone' => 'site_general_search:field_location_phone',
    'site_general_search:field_destination_email' => 'site_general_search:field_destination_email',
    'site_general_search:field_destination_phone' => 'site_general_search:field_destination_phone',
    'site_general_search:field_event_subtitle' => 'site_general_search:field_event_subtitle',
    'site_general_search:field_exhibition_subtitle' => 'site_general_search:field_exhibition_subtitle',
    'site_general_search:field_staff_email' => 'site_general_search:field_staff_email',
    'site_general_search:field_staff_first_name' => 'site_general_search:field_staff_first_name',
    'site_general_search:field_staff_job_title' => 'site_general_search:field_staff_job_title',
    'site_general_search:field_staff_last_name' => 'site_general_search:field_staff_last_name',
    'site_general_search:field_staff_middle_name' => 'site_general_search:field_staff_middle_name',
    'site_general_search:field_staff_phone' => 'site_general_search:field_staff_phone',
    'site_general_search:search_api_viewed' => 'site_general_search:search_api_viewed',
    'site_general_search:search_api_panelized' => 'site_general_search:search_api_panelized',
    'site_general_search:body:value' => 'site_general_search:body:value',
    'site_general_search:body:summary' => 'site_general_search:body:summary',
    'site_general_search:field_amenities:name' => 'site_general_search:field_amenities:name',
    'site_general_search:field_amenities:description' => 'site_general_search:field_amenities:description',
    'site_general_search:field_equipment:name' => 'site_general_search:field_equipment:name',
    'site_general_search:field_equipment:description' => 'site_general_search:field_equipment:description',
    'site_general_search:field_study_areas:name' => 'site_general_search:field_study_areas:name',
    'site_general_search:field_study_areas:description' => 'site_general_search:field_study_areas:description',
    'page_manager_pages:title' => 'page_manager_pages:title',
    'page_manager_pages:content' => 'page_manager_pages:content',
  );

  /* Display: Page */
  $handler = $view->new_display('page', 'Page', 'page');
  $handler->display->display_options['path'] = 'site-search';
  $export['site_multi_search'] = $view;

  $view = new view();
  $view->name = 'staff_directory';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'search_api_index_site_general_search';
  $view->human_name = 'Staff Directory';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'none';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['exposed_form']['options']['submit_button'] = 'Submit';
  $handler->display->display_options['exposed_form']['options']['reset_button_label'] = 'All Staff';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['style_options']['row_class'] = 'clearfix';
  $handler->display->display_options['row_plugin'] = 'fields';
  /* Field: Indexed Content: Staff Image Thumbnail */
  $handler->display->display_options['fields']['field_staff_image_thumbnail']['id'] = 'field_staff_image_thumbnail';
  $handler->display->display_options['fields']['field_staff_image_thumbnail']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_image_thumbnail']['field'] = 'field_staff_image_thumbnail';
  $handler->display->display_options['fields']['field_staff_image_thumbnail']['label'] = '';
  $handler->display->display_options['fields']['field_staff_image_thumbnail']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_staff_image_thumbnail']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_staff_image_thumbnail']['settings'] = array(
    'image_style' => 'thumbnail',
    'image_link' => 'content',
  );
  /* Field: Indexed Content: Node ID */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nid']['link_to_entity'] = 0;
  /* Field: Indexed Content: Staff First Name */
  $handler->display->display_options['fields']['field_staff_first_name']['id'] = 'field_staff_first_name';
  $handler->display->display_options['fields']['field_staff_first_name']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_first_name']['field'] = 'field_staff_first_name';
  $handler->display->display_options['fields']['field_staff_first_name']['label'] = '';
  $handler->display->display_options['fields']['field_staff_first_name']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_staff_first_name']['element_label_colon'] = FALSE;
  /* Field: Indexed Content: Staff Last Name */
  $handler->display->display_options['fields']['field_staff_last_name']['id'] = 'field_staff_last_name';
  $handler->display->display_options['fields']['field_staff_last_name']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_last_name']['field'] = 'field_staff_last_name';
  $handler->display->display_options['fields']['field_staff_last_name']['label'] = '';
  $handler->display->display_options['fields']['field_staff_last_name']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_staff_last_name']['alter']['text'] = '[field_staff_first_name] [field_staff_last_name]';
  $handler->display->display_options['fields']['field_staff_last_name']['element_label_colon'] = FALSE;
  /* Field: Indexed Content: Staff Job Title */
  $handler->display->display_options['fields']['field_staff_job_title']['id'] = 'field_staff_job_title';
  $handler->display->display_options['fields']['field_staff_job_title']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_job_title']['field'] = 'field_staff_job_title';
  $handler->display->display_options['fields']['field_staff_job_title']['label'] = '';
  $handler->display->display_options['fields']['field_staff_job_title']['element_label_colon'] = FALSE;
  /* Field: Indexed Content: Staff Subject Areas */
  $handler->display->display_options['fields']['field_staff_subject_areas']['id'] = 'field_staff_subject_areas';
  $handler->display->display_options['fields']['field_staff_subject_areas']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_subject_areas']['field'] = 'field_staff_subject_areas';
  $handler->display->display_options['fields']['field_staff_subject_areas']['label'] = '';
  $handler->display->display_options['fields']['field_staff_subject_areas']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_staff_subject_areas']['alter']['text'] = '<strong>I can help with </strong>[field_staff_subject_areas]';
  $handler->display->display_options['fields']['field_staff_subject_areas']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_staff_subject_areas']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_staff_subject_areas']['link_to_entity'] = 0;
  $handler->display->display_options['fields']['field_staff_subject_areas']['view_mode'] = 'full';
  $handler->display->display_options['fields']['field_staff_subject_areas']['bypass_access'] = 0;
  /* Field: Indexed Content: Staff Email */
  $handler->display->display_options['fields']['field_staff_email']['id'] = 'field_staff_email';
  $handler->display->display_options['fields']['field_staff_email']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_email']['field'] = 'field_staff_email';
  $handler->display->display_options['fields']['field_staff_email']['label'] = '';
  $handler->display->display_options['fields']['field_staff_email']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_staff_email']['element_label_colon'] = FALSE;
  /* Field: Indexed Content: Staff Phone */
  $handler->display->display_options['fields']['field_staff_phone']['id'] = 'field_staff_phone';
  $handler->display->display_options['fields']['field_staff_phone']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_phone']['field'] = 'field_staff_phone';
  $handler->display->display_options['fields']['field_staff_phone']['label'] = '';
  $handler->display->display_options['fields']['field_staff_phone']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_staff_phone']['alter']['text'] = '[field_staff_email] | [field_staff_phone] ';
  $handler->display->display_options['fields']['field_staff_phone']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_staff_phone']['empty'] = '[field_staff_email]';
  $handler->display->display_options['fields']['field_staff_phone']['hide_alter_empty'] = FALSE;
  /* Sort criterion: Indexed Content: Staff Alpha */
  $handler->display->display_options['sorts']['field_staff_glossary_index']['id'] = 'field_staff_glossary_index';
  $handler->display->display_options['sorts']['field_staff_glossary_index']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['sorts']['field_staff_glossary_index']['field'] = 'field_staff_glossary_index';
  /* Filter criterion: Indexed Content: Content type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'staff_profile' => 'staff_profile',
  );
  /* Filter criterion: Search: Fulltext search */
  $handler->display->display_options['filters']['search_api_views_fulltext']['id'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['filters']['search_api_views_fulltext']['field'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['operator'] = 'OR';
  $handler->display->display_options['filters']['search_api_views_fulltext']['exposed'] = TRUE;
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator_id'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['label'] = 'Fulltext search';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['identifier'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  /* Filter criterion: Indexed Content: Staff Subject Librarian */
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['id'] = 'field_staff_is_subject_librarian';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['field'] = 'field_staff_is_subject_librarian';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['exposed'] = TRUE;
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['expose']['operator_id'] = 'field_staff_is_subject_librarian_op';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['expose']['label'] = 'Staff Subject Librarian';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['expose']['operator'] = 'field_staff_is_subject_librarian_op';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['expose']['identifier'] = 'field_staff_is_subject_librarian';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['is_grouped'] = TRUE;
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['group_info']['label'] = 'Staff Subject Librarian';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['group_info']['identifier'] = 'field_staff_is_subject_librarian';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['group_info']['remember'] = FALSE;

  /* Display: Staff DIrectory */
  $handler = $view->new_display('panel_pane', 'Staff DIrectory', 'staff_directory_pane');
  $handler->display->display_options['exposed_block'] = TRUE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Indexed Content: Staff Image Thumbnail */
  $handler->display->display_options['fields']['field_staff_image_thumbnail']['id'] = 'field_staff_image_thumbnail';
  $handler->display->display_options['fields']['field_staff_image_thumbnail']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_image_thumbnail']['field'] = 'field_staff_image_thumbnail';
  $handler->display->display_options['fields']['field_staff_image_thumbnail']['label'] = '';
  $handler->display->display_options['fields']['field_staff_image_thumbnail']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_staff_image_thumbnail']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_staff_image_thumbnail']['settings'] = array(
    'image_style' => 'staff_profile_photo_thumbnail',
    'image_link' => 'content',
  );
  /* Field: Indexed Content: Node ID */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nid']['link_to_entity'] = 0;
  /* Field: Indexed Content: Staff First Name */
  $handler->display->display_options['fields']['field_staff_first_name']['id'] = 'field_staff_first_name';
  $handler->display->display_options['fields']['field_staff_first_name']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_first_name']['field'] = 'field_staff_first_name';
  $handler->display->display_options['fields']['field_staff_first_name']['label'] = '';
  $handler->display->display_options['fields']['field_staff_first_name']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_staff_first_name']['element_label_colon'] = FALSE;
  /* Field: Indexed Content: Staff Middle Name */
  $handler->display->display_options['fields']['field_staff_middle_name']['id'] = 'field_staff_middle_name';
  $handler->display->display_options['fields']['field_staff_middle_name']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_middle_name']['field'] = 'field_staff_middle_name';
  $handler->display->display_options['fields']['field_staff_middle_name']['label'] = '';
  $handler->display->display_options['fields']['field_staff_middle_name']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_staff_middle_name']['element_label_colon'] = FALSE;
  /* Field: Indexed Content: Staff Last Name */
  $handler->display->display_options['fields']['field_staff_last_name']['id'] = 'field_staff_last_name';
  $handler->display->display_options['fields']['field_staff_last_name']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_last_name']['field'] = 'field_staff_last_name';
  $handler->display->display_options['fields']['field_staff_last_name']['label'] = '';
  $handler->display->display_options['fields']['field_staff_last_name']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_staff_last_name']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_staff_last_name']['alter']['text'] = '[field_staff_first_name] [field_staff_middle_name] [field_staff_last_name]';
  $handler->display->display_options['fields']['field_staff_last_name']['element_label_colon'] = FALSE;
  /* Field: Content: Link */
  $handler->display->display_options['fields']['view_node']['id'] = 'view_node';
  $handler->display->display_options['fields']['view_node']['table'] = 'views_entity_node';
  $handler->display->display_options['fields']['view_node']['field'] = 'view_node';
  $handler->display->display_options['fields']['view_node']['label'] = '';
  $handler->display->display_options['fields']['view_node']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['view_node']['alter']['text'] = '[field_staff_last_name]';
  $handler->display->display_options['fields']['view_node']['element_label_colon'] = FALSE;
  /* Field: Indexed Content: Staff Job Title */
  $handler->display->display_options['fields']['field_staff_job_title']['id'] = 'field_staff_job_title';
  $handler->display->display_options['fields']['field_staff_job_title']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_job_title']['field'] = 'field_staff_job_title';
  $handler->display->display_options['fields']['field_staff_job_title']['label'] = '';
  $handler->display->display_options['fields']['field_staff_job_title']['element_label_colon'] = FALSE;
  /* Field: Indexed Content: Staff Subject Areas */
  $handler->display->display_options['fields']['field_staff_subject_areas']['id'] = 'field_staff_subject_areas';
  $handler->display->display_options['fields']['field_staff_subject_areas']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_subject_areas']['field'] = 'field_staff_subject_areas';
  $handler->display->display_options['fields']['field_staff_subject_areas']['label'] = '';
  $handler->display->display_options['fields']['field_staff_subject_areas']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_staff_subject_areas']['alter']['text'] = '<strong>I can help with </strong>[field_staff_subject_areas]';
  $handler->display->display_options['fields']['field_staff_subject_areas']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_staff_subject_areas']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_staff_subject_areas']['link_to_entity'] = 0;
  $handler->display->display_options['fields']['field_staff_subject_areas']['view_mode'] = 'full';
  $handler->display->display_options['fields']['field_staff_subject_areas']['bypass_access'] = 0;
  /* Field: Indexed Content: Staff Email */
  $handler->display->display_options['fields']['field_staff_email']['id'] = 'field_staff_email';
  $handler->display->display_options['fields']['field_staff_email']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_email']['field'] = 'field_staff_email';
  $handler->display->display_options['fields']['field_staff_email']['label'] = '';
  $handler->display->display_options['fields']['field_staff_email']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_staff_email']['element_label_colon'] = FALSE;
  /* Field: Indexed Content: Staff Phone */
  $handler->display->display_options['fields']['field_staff_phone']['id'] = 'field_staff_phone';
  $handler->display->display_options['fields']['field_staff_phone']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['fields']['field_staff_phone']['field'] = 'field_staff_phone';
  $handler->display->display_options['fields']['field_staff_phone']['label'] = '';
  $handler->display->display_options['fields']['field_staff_phone']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_staff_phone']['alter']['text'] = '[field_staff_email] | [field_staff_phone] ';
  $handler->display->display_options['fields']['field_staff_phone']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_staff_phone']['empty'] = '[field_staff_email]';
  $handler->display->display_options['fields']['field_staff_phone']['hide_alter_empty'] = FALSE;
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Indexed Content: Content type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'staff_profile' => 'staff_profile',
  );
  $handler->display->display_options['filters']['type']['group'] = 1;
  /* Filter criterion: Indexed Content: Staff Subject Librarian */
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['id'] = 'field_staff_is_subject_librarian';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['field'] = 'field_staff_is_subject_librarian';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['value'] = array();
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['group'] = 1;
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['exposed'] = TRUE;
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['expose']['operator_id'] = 'field_staff_is_subject_librarian_op';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['expose']['label'] = 'Staff Subject Librarian';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['expose']['operator'] = 'field_staff_is_subject_librarian_op';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['expose']['identifier'] = 'field_staff_is_subject_librarian';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['expose']['reduce'] = 0;
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['is_grouped'] = TRUE;
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['group_info']['label'] = 'Show';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['group_info']['identifier'] = 'field_staff_is_subject_librarian';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['group_info']['optional'] = FALSE;
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['group_info']['widget'] = 'radios';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['group_info']['default_group'] = '1';
  $handler->display->display_options['filters']['field_staff_is_subject_librarian']['group_info']['group_items'] = array(
    1 => array(
      'title' => 'All Staff',
      'operator' => '=',
      'value' => array(
        0 => '0',
        1 => '1',
      ),
    ),
    2 => array(
      'title' => 'Subject Librarians only',
      'operator' => '=',
      'value' => array(
        0 => 0,
      ),
    ),
  );
  /* Filter criterion: Search: Fulltext search */
  $handler->display->display_options['filters']['search_api_views_fulltext']['id'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['table'] = 'search_api_index_site_general_search';
  $handler->display->display_options['filters']['search_api_views_fulltext']['field'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['operator'] = 'OR';
  $handler->display->display_options['filters']['search_api_views_fulltext']['group'] = 1;
  $handler->display->display_options['filters']['search_api_views_fulltext']['exposed'] = TRUE;
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator_id'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['identifier'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  $handler->display->display_options['inherit_panels_path'] = '1';
  $export['staff_directory'] = $view;

  return $export;
}
