<?php

/**
 * @file
 * Main code file for uclalib_opening_hours module.
 */

include_once 'uclalib_opening_hours.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function uclalib_opening_hours_ctools_plugin_directory($owner, $plugin_type) {
  switch ("$owner:$plugin_type") {
    case 'ctools:content_types':
      return "plugins/$owner/$plugin_type";
  }

  return NULL;
}

/**
 * Abbreviate a time string to the required format.
 *
 * @param $time
 *   The time as 'HH:MM:SS';
 * @return string
 *   The time with the abbreviated form. Ex: 2p, 12:30a
 */
function _uclalib_opening_hours_short_time($time) {
  $matches = array();

  if (preg_match('/^([0-9]{2}):([0-9]{2}):([0-9]{2})$/', $time, $matches)) {
    $hour = $matches[1];
    $minute = $matches[2];

    $ap = 'a';
    $hour = ltrim($hour, '0');
    if ($hour > 12) {
      $hour = $hour - 12;
      $ap = 'p';
    }

    $time = $hour;

    if ($minute != '00') {
      $time .= ':' . $minute;
    }

    $time .= $ap;
  }

  return $time;
}

/**
 * Get the short custom text for days of the week.
 *
 * @param $dow
 * @return mixed
 */
function _uclalib_opening_hours_short_day($dow) {
  $strs = array(
    'Su',
    'M',
    'Tu',
    'W',
    'Th',
    'F',
    'Sa',
  );

  if (isset($strs[$dow])) {
    return $strs[$dow];
  }
}

/**
 * Generate hours table header.
 */
function uclalib_opening_hours_generate_table_header() {
  // Get the date of the first day of this week.
  $day = date_create('this week');

  // Create an interval of 1 day to add to the date for each week day.
  $interval = DateInterval::createFromDateString('1 day');

  $header = array(array('data' => '','class' => array('empty-header-cell')));
  for ($i = 0; $i < 7; $i++) {
    $day_str = _uclalib_opening_hours_short_day($day->format('w'));
    $header_cell = array(
      'data' => $day_str . ' ' . $day->format('d'),
      'class' => array(drupal_html_class('day-' . $day->format('D'))),
    );

    // If current day add a class.
    if ($day->format('d') == date_create()->format('d')) {
      $header_cell['class'][] = 'current-day';
    }

    $header[] = $header_cell;

    // Add 1 day.
    $day->add($interval);
  }

  return $header;
}

function uclalib_opening_hours_generate_table_rows($nodes) {
  $rows = array();

  // Create an interval of 1 day to add to the date for each week day.
  $interval = DateInterval::createFromDateString('1 day');

  foreach ($nodes as $nid => $title) {
    // Get the first day of the week again.
    $day = date_create('this week');

    // Add the title to the first column.
    $row = array(array('data' => $title, 'class' => array('title')));

    // Fetch opening hours for each day.
    for ($i = 0; $i < 7; $i++) {
      $date = $day->format('Y-m-d');
      $oh = db_select('opening_hours', 'oh')
        ->fields('oh', array('start_time', 'end_time'))
        ->condition('nid', $nid)
        ->condition('date', $date)
        ->execute()
        ->fetchAssoc();

      $start_time = _uclalib_opening_hours_short_time($oh['start_time']);
      $end_time = _uclalib_opening_hours_short_time($oh['end_time']);
      $class = (empty($start_time) && empty($end_time)) ? 'closed' : 'open';
      $row_cell = array(
        'data' => $start_time . '-' . $end_time,
        'class' => array(drupal_html_class('day-' . $day->format('D')), $class),
      );

      // If current day add a class.
      if ($day->format('d') == date_create()->format('d')) {
        $row_cell['class'][] = 'current-day';
      }

      $row[] = $row_cell;

      // Add one day.
      $day->add($interval);
    }
    $rows[] = $row;
  }

  return $rows;
}

function uclalib_opening_hours_generate_table($node) {
  // Generate a header with the days of the week.
  $header = uclalib_opening_hours_generate_table_header();

  // Check for alternate name.
  $title = isset($node->field_location_oh_name[LANGUAGE_NONE][0]['value']) ?
    $node->field_location_oh_name[LANGUAGE_NONE][0]['value'] : $node->title;

  // List of nodes that will be displayed. By default the passed node.
  $nodes = array(
    $node->nid => check_plain($title),
  );

  if (isset($node->field_location_destinations[LANGUAGE_NONE]) && is_array($node->field_location_destinations[LANGUAGE_NONE])) {
    foreach ($node->field_location_destinations[LANGUAGE_NONE] as $value) {
      if (isset($value['target_id'])) {
        // @todo: avoid node_load.
        $dest_node = node_load($value['target_id']);

        $title = isset($dest_node->field_destination_oh_name[LANGUAGE_NONE][0]['value']) ?
          $dest_node->field_destination_oh_name[LANGUAGE_NONE][0]['value'] : $dest_node->title;
        $nodes[$dest_node->nid] = check_plain($title);
      }
    }
  }

  $rows = uclalib_opening_hours_generate_table_rows($nodes);

  $output = theme('table', array(
    'header' => $header,
    'rows' => $rows,
    'attributes' => array('class' => array('opening-hours-week')),
  ));

  return $output;
}
