<?php
/**
 * @file
 * Code for the UCLALIB Architecture feature.
 */

include_once 'uclalib_arch.features.inc';

/**
 * Implements hook_flush_caches().
 */
function uclalib_arch_flush_caches() {
  if (module_exists('bean')) {
    // Ensure permissions to view all bean types are enabled for anonymous
    // and authenticated users.

    $rids = array(
      DRUPAL_ANONYMOUS_RID,
      DRUPAL_AUTHENTICATED_RID,
    );


    // Permission for each entity type.
    bean_reset(TRUE);
    $perms = array();
    foreach (bean_get_types() as $bean_type) {
      $bean_type_name = check_plain($bean_type->type);
      $perms[] = "view any $bean_type_name bean";
    }

    foreach ($rids as $rid) {
      user_role_grant_permissions($rid, $perms);
    }
  }
}

/**
 * Implements hook_date_format_types().
 */
function uclalib_arch_date_format_types() {
  return array(
    'month_with_date' => t('Month with date'),
  );
  return array(
    'month' => t('Month'),
  );
  return array(
    'day' => t('Day'),
  );
  return array(
    'time' => t('Time'),
  );
}

/**
 * Implements hook_icon_bundles().
 *
 * Define UCLALIB custom icon set.
 */
function uclalib_arch_icon_bundles() {
  $bundles = array();
  $bundles['uclalib'] = array(
    'icons' => array (
      'todo' => 'todo',
      'start' => 'start',
      'search' => 'search',
      'printer' => 'printer',
      'printer-color' => 'printer-color',
      'news' => 'news',
      'more' => 'more',
      'hours' => 'hours',
      'help' => 'help',
      'copy' => 'copy',
      'copy-color' => 'copy-color',
      'cash' => 'cash',
      'arrow-right' => 'arrow-right',
      'home' => 'home',
      'email' => 'email',
      'telephone' => 'telephone',
      'specialist' => 'specialist',
      'calendar' => 'calendar',
      'address' => 'address',
      'web' => 'web',
    ),
    'name' => 'uclalib',
    'provider' => 'icomoon',
    'settings' => array (
      'ie7' => 0,
      'tag' => 'span',
      'prefix' => 'icon-',
      'metadata' => array (
        'fontFamily' => 'icomoon',
      ),
      'showGlyphs' => true,
      'metrics' => array (
        'emSize' => 512,
        'baseline' => 6.25,
        'whitespace' => 50,
      ),
      'resetPoint' => 58880,
      'showQuickUse' => true,
      'quickUsageToken' => false,
      'showMetrics' => true,
      'showMetadata' => false,
    ),
    'status' => 1,
    'title' => 'UCLALIB Icons',
    'version' => '',
    '#attached' => array (
      'icomoon_process_attached' => array (
        0 => array (
          0 => 'uclalib',
        ),
      ),
    ),
    'path' => 'sites/all/themes/uclalib_omega/icons',
    'render' => 'sprite',
    'import' => true,
    'database' => true,
  );

  return $bundles;
}
